config/urls.py
"""URL configuration for config project."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import TemplateView
from djpress.sitemaps import (
    CategorySitemap,
    DateBasedSitemap,
    PageSitemap,
    PostSitemap,
)

from config.sitemaps import StaticSitemap

sitemaps = {
    "posts": PostSitemap,
    "pages": PageSitemap,
    "categories": CategorySitemap,
    "archives": DateBasedSitemap,
    "static": StaticSitemap,
}

urlpatterns = []

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        path("404", TemplateView.as_view(template_name="404.html")),
        path("500", TemplateView.as_view(template_name="500.html")),
    ]

urlpatterns += [
    path(f"{settings.ADMIN_URL}/", admin.site.urls),
    path("healthcheck/", view=include("healthcheck_app.urls")),
    path("contact/", view=include("contact_form.urls")),
    path("utils/timezones/", view=include("timezone_converter.urls")),
    path("utils/markdown-editor/", view=include("markdown_editor.urls")),
    path("utils/spf/", view=include("spf_generator.urls")),
    path("utils/home/", view=include("home.urls")),
    path("utils/__debugging__/", view=include("debugging_app.urls")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("", include("djpress.urls")),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

contact_form/urls.py
"""URLs for contact form app."""

from django.urls import path

from contact_form.views import contact_form

app_name = "contact_form"

urlpatterns = [
    path("", contact_form, name="contact_form"),
]

home/urls.py
"""URLs for home app."""

from django.urls import path

from home.views import home_view

app_name = "home"

urlpatterns = [
    path("", home_view, name="home"),
]

templates/snippets/header.html
{% load djpress_tags %}
<header class="navbar navbar-expand navbar-dark mb-3 border-bottom border-1 border-success-subtle">
  <div class="container px-1 px-sm-3">
    {% site_title_link link_class="navbar-brand fs-4 me-sm-3 me-0 px-sm-0 px-0" %}
    <ul class="navbar-nav me-auto">
      {% get_pages as pages %}
      {% for page in pages %}
        {% if not page.is_child %}
          <li class="nav-item">
            <a href="{{ page.url }}" class="nav-link px-sm-2 px-1">{{ page.title }}</a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'admin:index' %}"
             class="nav-link icon-link px-sm-2 px-1">
            {% include "svg/house-gear.svg" %}
            <span class="d-none d-md-inline">Admin</span>
          </a>
        </li>
      {% endif %}
      <li class="nav-item">
        <a href="{% search_url %}" class="nav-link icon-link px-sm-2 px-1">
          {% include "svg/search.svg" %}
          <span class="d-none d-md-inline">Search</span>
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url "contact_form:contact_form" %}"
           hx-get="{% url 'contact_form:contact_form' %}"
           hx-target="#contactForm"
           data-bs-toggle="modal"
           data-bs-target="#contactFormModal"
           class="nav-link icon-link px-sm-2 px-1">
          {% include "svg/email-heart.svg" %}
          <span class="d-none d-md-inline">Email</span>
        </a>
      </li>
      <li class="nav-item">
        <a rel="me"
           href="https://fosstodon.org/@stuartm"
           class="nav-link icon-link px-sm-2 px-1">
          {% include "svg/mastodon.svg" %}
          <span class="d-none d-md-inline">Social</span>
        </a>
      </li>
      <li class="nav-item">
        <a href="{% get_rss_url %}" class="nav-link icon-link px-sm-2 px-1">
          {% include "svg/rss-fill.svg" %}
          <span class="d-none d-md-inline">RSS</span>
        </a>
      </li>
    </ul>
  </div>
</header>

templates/snippets/messages.html
{% if messages %}
  {% for message in messages %}<div class="container-fluid message {{ message.tags }}">{{ message }}</div>{% endfor %}
{% endif %}