config/urls.py
"""URL configuration for config project."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import TemplateView
from djpress.sitemaps import (
    CategorySitemap,
    DateBasedSitemap,
    PageSitemap,
    PostSitemap,
)

from config.sitemaps import StaticSitemap

sitemaps = {
    "posts": PostSitemap,
    "pages": PageSitemap,
    "categories": CategorySitemap,
    "archives": DateBasedSitemap,
    "static": StaticSitemap,
}

urlpatterns = []

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        path("404", TemplateView.as_view(template_name="404.html")),
        path("500", TemplateView.as_view(template_name="500.html")),
    ]

urlpatterns += [
    path(f"{settings.ADMIN_URL}/", admin.site.urls),
    path("healthcheck/", view=include("healthcheck_app.urls")),
    path("contact/", view=include("contact_form.urls")),
    path("utils/timezones/", view=include("timezone_converter.urls")),
    path("utils/markdown-editor/", view=include("markdown_editor.urls")),
    path("utils/spf/", view=include("spf_generator.urls")),
    path("utils/home/", view=include("home.urls")),
    path("utils/__debugging__/", view=include("debugging_app.urls")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("", include("djpress.urls")),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

home/urls.py
"""URLs for home app."""

from django.urls import path

from home.views import home_view

app_name = "home"

urlpatterns = [
    path("", home_view, name="home"),
]

timezone_converter/urls.py
"""URLs for timezone_converter app."""

from django.urls import path

from timezone_converter.views import convert, converter

app_name = "timezone_converter"

urlpatterns = [
    path("", converter, name="converter"),
    path("convert/", convert, name="convert"),
]

timezone_converter/views.py
"""Views for the timezone_converter app."""

from datetime import datetime
from typing import TYPE_CHECKING
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from django.shortcuts import render

if TYPE_CHECKING:
    from django.http import HttpRequest, HttpResponse


# A simple view to display the converter HTML template.
def converter(request: HttpRequest) -> HttpResponse:
    """Display the converter HTML template."""
    return render(
        request,
        "timezone_converter/converter.html",
    )


# A view to receive a timestamp and timezone POSTed from the converter form and return
# the converted time using a template.
def convert(request: HttpRequest) -> HttpResponse:
    """Convert a timestamp to a different timezone and display the result."""
    # Get the timestamp and timezone from the POST request.
    # pyrefly: ignore [bad-assignment]
    timestamp: str | None = request.POST.get("timestamp")
    # pyrefly: ignore [bad-assignment]
    timezone: str | None = request.POST.get("timezone")

    error_message: str = ""

    if not timezone or not timestamp:
        error_message = "Please provide a timestamp and timezone."
        return render(
            request,
            "timezone_converter/converted.html",
            {"error_message": error_message},
        )

    # Convert the timestamp to a datetime object.
    try:
        datetime_obj: datetime = datetime.fromisoformat(timestamp)
    except ValueError:
        error_message = "Invalid timestamp. Please use the ISO 8601 format."
        return render(
            request,
            "timezone_converter/converted.html",
            {"error_message": error_message},
        )

    # Check the converted timestamp is timezone aware
    if datetime_obj.tzinfo is None:
        error_message = (
            "The timestamp provided must be timezone aware. For example, use 'Z' for UTC, or provide an offset."
        )
        return render(
            request,
            "timezone_converter/converted.html",
            {"error_message": error_message},
        )

    # Check that the timezone is valid.
    try:
        ZoneInfo(timezone)
    except ZoneInfoNotFoundError:
        error_message = "Invalid timezone. Please use a valid timezone."
        return render(
            request,
            "timezone_converter/converted.html",
            {"error_message": error_message},
        )

    return render(
        request,
        "timezone_converter/converted.html",
        {"timestamp": datetime_obj, "timezone": timezone},
    )

timezone_converter/templates/timezone_converter/converted.html
{% load tz %}
{% if error_message %}
  {{ error_message }}
{% else %}
  {% timezone timezone %}
  <p>Converted time: {{ timestamp }}</p>
  <table class="table">
    <thead>
      <tr>
        <th>Format</th>
        <th>Time</th>
      </tr>
    </thead>
    <tr>
      <td>ISO 8601</td>
      <td>{{ timestamp|date:"c" }}</td>
    </tr>
    <tr>
      <td>RFC 5322</td>
      <td>{{ timestamp|date:"r" }}</td>
    </tr>
    <tr>
      <td>Short Date</td>
      <td>{{ timestamp|date:"d/m/Y" }}</td>
    </tr>
    <tr>
      <td>Long Date</td>
      <td>{{ timestamp|date:"l, j F Y" }}</td>
    </tr>
    <tr>
      <td>Short Time</td>
      <td>{{ timestamp|date:"H:i" }}</td>
    </tr>
    <tr>
      <td>Long Time</td>
      <td>{{ timestamp|date:"H:i:s" }}</td>
    </tr>
  </table>
{% endtimezone %}
{% endif %}

timezone_converter/templates/timezone_converter/converter.html
{% extends "_base.html" %}
{% load static %}
{% block title %}Timezone Converter{% endblock %}
{% comment %} This removes the RSS link {% endcomment %}
{% block head_close %}{% endblock %}
{% block content %}
  <h1>Timezone Converter</h1>
  <div class="row">
    <div class="col-12 col-xl-6">
      <form>
        <label for="timestamp" class="form-label">
          Enter a timestamp in ISO 8601 format:
          <input class="form-control"
                 type="text"
                 name="timestamp"
                 id="timestamp"
                 value="2024-01-01T00:00:00Z" />
        </label>
        <label for="timezone" class="form-label">
          Enter a timezone to conver to:
          <input class="form-control"
                 type="text"
                 name="timezone"
                 id="timezone"
                 value="Pacific/Auckland" />
        </label>
        <button hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                hx-post="{% url 'timezone_converter:convert' %}"
                hx-params="timestamp, timezone"
                hx-target="#converted"
                type="button"
                class="btn btn-primary">Convert</button>
      </form>
    </div>
    <div class="col-12 col-xl-6">
      <span id="converted"></span>
    </div>
  </div>
{% endblock content %}